# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Mikey Wills
url: http://muke.me
description: Where Idiots Come to Die
twitter: mukealicious
gravatar_url: http://gravatar.com/avatar/7f3afdc92cd5fb8bbdf12d8d33a88839
disqus_id: 

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background: 

# Footer
footer_title: About Mukey
footer_description: Just killing time between meals.
instagram_access_token:
# Social
social_links_title: Picture Me Rollin
github_url: http://github.com/mukealicious
behance_url: 
cargo_url: 
delicious_url: 
dribbble_url: 
etsy_url: 
facebook_url: 
ffffound_url: 
flickr_url: 
formspring_url: 
forrst_url: 
foursquare_url: 
google_plus_url: 
instagram_url: 
lastfm_url: 
linkedin_url: 
pinterest_url: 
quora_url: 
rdio_url: 
skype_url: 
slideshare_url: 
soundcloud_url: 
spotify_url: 
stumble_upon_url: 
twitter_url: 
vimeo_url: 
website_url: 
youtube_url: 
email: mikey@muke.me