# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

# User Options
name: Mikey Wills
url: http://muke.me
description: Where Idiots Come to Die
twitter: mukealicious
github: mukealicious
gravatar_url: http://gravatar.com/avatar/7f3afdc92cd5fb8bbdf12d8d33a88839
disqus_id: 

# Color Options
text_color: '#444444'
accent_color: '#11af8c'
hover_color: '#0e7c63'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_text_color: '#cefff4'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#88e9d3'
header_subtle_border: '#4acf9b'
header_background: '#0e9879'
post_background: '#ffffff'
background: '#fcfcfc'

#Footer
footer_title: About Mukey
footer_description: Just killing time between meals.
twitter_widget_embed: 
instagram_access_token:
#Social
social_links_title: Picture Me Rollin
twitter: mukealicious
github_url: mukealicious
behance_url: mukealicious
cargo_url: mukealicious
delicious_url: mukealicious
dribbble_url: mukealicious
etsy_url: mukealicious
facebook_url: mukealicious
ffffound_url: mukealicious
flickr_url: mukealicious
formspring_url: mukealicious
forrst_url: mukealicious
foursquare_url: mukealicious
google_plus_url: mukealicious
instagram_url: mukealicious
lastfm_url: mukealicious
linkedin_url: mukealicious
pinterest_url: mukealicious
quora_url: mukealicious
rdio_url: mukealicious
skype_url: mukealicious
slideshare_url: mukealicious
soundcloud_url: mukealicious
spotify_url: mukealicious
stumble_upon_url: mukealicious
twitter_url: mukealicious
vimeo_url: mukealicious
website_url: mukealicious
youtube_url: mukealicious
email: mikey@muke.me