# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Mikey Wills
url: http://muke.me
description: Where Idiots Come to Die
email: mikey@muke.me
twitter: mukealicious
icon_url: http://gravatar.com/avatar/7f3afdc92cd5fb8bbdf12d8d33a88839
disqus_shortname: mikeywills

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: About Mukey
footer_description: 'A designer based out of Orange County, CA. Front end developer at Style Hatch. Just killing time between meals.'
social_links_title: Picture Me Rollin
github_url: test
flickr_url: test
instagram_url: test
vimeo_url: test
facebook_url: test
google_plus_url: test
pinterest_url: test
tumblr_url: test
linkedin_url: test
dribbble_url: test
lastfm_url: test
rdio_url: test
spotify_url: test
skype_url: test
soundcloud_url: test
behance_url: test
